
all:
	cd ../build/; \
	make -f makefile all

run:
	cd ../build/; \
	make -f makefile run

re:
	cd ../build/; \
	make -f makefile re

rerun:
	cd ../build/; \
	make -f makefile rerun

clean:
	cd ../build/; \
	make -f makefile clean
